name: build-prs

on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.16
      uses: actions/setup-go@37335c7bb261b353407cff977110895fa0b4f7d8
      with:
        go-version: 1.16
      id: go

    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

    - name: build binary
      run: go build -ldflags="-s -w" -o bin/dataset-tweeter main.go

    - name: Execute notifier
      run: ./bin/dataset-tweeter

