name: tweet-datasets

on:
  schedule:
    - cron: '15 17 * * *'

jobs:
  scrape-and-tweet:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@9fbc767707c286e568c92927bbf57d76b73e0892
      with:
        go-version: 1.14
      id: go

    - uses: actions/checkout@01aecccf739ca6ff86c0539fbc67a7a5007bbc81

    - name: build binary
      run: |
        go build -ldflags="-s -w" -o bin/dataset-tweeter main.go

    - name: Install & setup mc
      run: |
        wget https://dl.min.io/client/mc/release/linux-amd64/mc
        chmod +x mc
        ./mc config host add c4m ${{ secrets.s3_url }} ${{ secrets.s3_accesskey }} ${{ secrets.s3_secretkey }} --api S3v4

    - name: Get data from yesterday
      run: |
        export YESTERDAY=$(date -Idate -d yesterday)
        ./mc cp "c4m/codeformuenster/dkan-opendata-portal-ms/data-${YESTERDAY}.json" "data-${YESTERDAY}.json"
        mv "data-${YESTERDAY}.json" data-previous.json

    - name: Execute notifier
      run: ./bin/dataset-tweeter -enable-tweeter=false -local-path=./data-previous.json -consumer-key=${{ secrets.twitter_consumerkey }} -consumer-secret=${{ secrets.twitter_consumersecret }} -access-token=${{ secrets.twitter_accesstoken }} -access-secret=${{ secrets.twitter_accesssecret }}

    - name: Upload data of today if changed
      run: |
        export TODAY=$(date -Idate)
        ls -lah
        if [ -n "$(cmp data-${TODAY}.json data-previous.json)" ]; then
          printf 'file "%s" is different from "%s". Uploading..\n' "data-${TODAY}.json" "data-previous.json"
          ./mc cp "data-${TODAY}.json" "c4m/codeformuenster/dkan-opendata-portal-ms/data-${TODAY}.json"
        fi
