name: tweet-datasets

on:
  schedule:
    - cron: '0 8-20/2 * * *'
jobs:
  scrape-and-tweet:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.14
      uses: actions/setup-go@9fbc767707c286e568c92927bbf57d76b73e0892
      with:
        go-version: 1.14
      id: go

    - uses: actions/checkout@01aecccf739ca6ff86c0539fbc67a7a5007bbc81

    - name: build binary
      run: go build -ldflags="-s -w" -o bin/dataset-tweeter main.go

    - name: Setup config file
      run: echo '{"twitter":{"consumerKey":"${{ secrets.twitter_consumerkey }}","consumerSecret":"${{ secrets.twitter_consumersecret }}","accessToken":"${{ secrets.twitter_accesstoken }}","accessSecret":"${{ secrets.twitter_accesssecret }}"},"s3":{"region":"${{ secrets.s3_region }}","endpoint":"${{ secrets.s3_endpoint }}","bucket":"${{ secrets.s3_bucket }}","path":"${{ secrets.s3_path }}","accessKeyId":"${{ secrets.s3_accesskey }}","secretAccessKey":"${{ secrets.s3_secretkey }}"}}' > config.json

    - name: Execute notifier
      run: ./bin/dataset-tweeter -enable-twitter=true
