name: tweet-datasets

on:
  push:
    branches:
      - master
  #schedule:
  #  - cron: '0 16-21/2 * * *'
  workflow_dispatch: {}
jobs:
  scrape-and-tweet:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go 1.20
      uses: actions/setup-go@v3
      with:
        go-version: "1.20"
        check-latest: true
        cache: true

    - name: build binary
      env:
        GOAMD64: v3
      run: go build -ldflags="-s -w" -o bin/dataset-tooter main.go

    - name: Setup config file
      run: echo '{"mastodon":{"server":"https://muenster.im","clientID":"${{ secrets.mastodon_client_id }}","clientSecret":"${{ secrets.mastodon_client_secret }}","accessToken":"${{ secrets.mastodon_access_token }}","email":"${{ secrets.mastodon_email }}","password":"${{ secrets.mastodon_password }}"},"s3":{"region":"${{ secrets.s3_region }}","endpoint":"${{ secrets.s3_endpoint }}","bucket":"${{ secrets.s3_bucket }}","path":"${{ secrets.s3_path }}","accessKeyId":"${{ secrets.s3_accesskey }}","secretAccessKey":"${{ secrets.s3_secretkey }}"}}' > config.json

    - name: Execute notifier
      run: ./bin/dataset-tooter -enable-tooter=true -allow-empty -toot-unlisted
