name: tweet-datasets

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 16-21/2 * * *'
jobs:
  scrape-and-tweet:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.15
      uses: actions/setup-go@3b4dc6cbed1779f759b9c638cb83696acea809d1
      with:
        go-version: 1.15
      id: go

    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

    - name: build binary
      run: go build -ldflags="-s -w" -o bin/dataset-tweeter main.go

    - name: Setup config file
      run: echo '{"twitter":{"consumerKey":"${{ secrets.twitter_consumerkey }}","consumerSecret":"${{ secrets.twitter_consumersecret }}","accessToken":"${{ secrets.twitter_accesstoken }}","accessSecret":"${{ secrets.twitter_accesssecret }}"},"s3":{"region":"${{ secrets.s3_region }}","endpoint":"${{ secrets.s3_endpoint }}","bucket":"${{ secrets.s3_bucket }}","path":"${{ secrets.s3_path }}","accessKeyId":"${{ secrets.s3_accesskey }}","secretAccessKey":"${{ secrets.s3_secretkey }}"}}' > config.json

    - name: Execute notifier
      run: ./bin/dataset-tweeter -enable-twitter=true
