name: tweet-datasets

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 16-21/2 * * *'
  workflow_dispatch: {}
jobs:
  scrape-and-tweet:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.18
      uses: actions/setup-go@f6164bd8c8acb4a71fb2791a8b6c4024ff038dab
      with:
        go-version: 1.18
      id: go

    - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846

    - name: build binary
      env:
        GOAMD64: v3
      run: go build -ldflags="-s -w" -o bin/dataset-tweeter main.go

    - name: Setup config file
      run: echo '{"twitter":{"consumerKey":"${{ secrets.twitter_consumerkey }}","consumerSecret":"${{ secrets.twitter_consumersecret }}","accessToken":"${{ secrets.twitter_accesstoken }}","accessSecret":"${{ secrets.twitter_accesssecret }}"},"s3":{"region":"${{ secrets.s3_region }}","endpoint":"${{ secrets.s3_endpoint }}","bucket":"${{ secrets.s3_bucket }}","path":"${{ secrets.s3_path }}","accessKeyId":"${{ secrets.s3_accesskey }}","secretAccessKey":"${{ secrets.s3_secretkey }}"}}' > config.json

    - name: Execute notifier
      run: ./bin/dataset-tweeter -enable-twitter=true
